{
 "title": "Teamspeak Full",
 "description": "Sample dashboard for GitHub project https://github.com/TilmannF/teamspeak-prometheus",
 "tags": [
  "prometheus",
  "teamspeak"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(teamspeak_virtualserver_uptime, job)"
   },
   {
    "name": "instance",
    "label": "Instance:",
    "query": "label_values(teamspeak_virtualserver_uptime{job=\"$job\"}, instance)"
   },
   {
    "name": "virtualserver",
    "label": "Virtual Server:",
    "query": "label_values(teamspeak_virtualserver_uptime{instance=\"$instance\",job=\"$job\"}, virtualserver_name)"
   },
   {
    "name": "maxclients",
    "query": "query_result(teamspeak_virtualserver_maxclients{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Connected Clients",
   "type": "singlestat",
   "description": "teamspeak_virtualserver_clientsonline - teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "teamspeak_virtualserver_clientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} - teamspeak_virtualserver_queryclientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Max clients",
   "type": "singlestat",
   "description": "Based on teamspeak_virtualserver_maxclients",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "teamspeak_virtualserver_maxclients{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Reserved slots",
   "type": "singlestat",
   "description": "teamspeak_virtualserver_reserved_slots",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "teamspeak_virtualserver_reserved_slots{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Channels online",
   "type": "singlestat",
   "description": "Based on teamspeak_virtualserver_channelsonline",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "teamspeak_virtualserver_channelsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "teamspeak_virtualserver_uptime",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "teamspeak_virtualserver_uptime{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "description": "Based on teamspeak_virtualserver_clientsonline & teamspeak_virtualserver_queryclientsonline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "teamspeak_virtualserver_clientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} - teamspeak_virtualserver_queryclientsonline{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "graph",
   "description": "Based on teamspeak_virtualserver_total_packetloss_total, teamspeak_virtualserver_total_packetloss_speech, teamspeak_virtualserver_total_packetloss_keepalive, teamspeak_virtualserver_total_packetloss_control",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_packetloss_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Speech"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Keepalive"
    },
    {
     "expr": "teamspeak_virtualserver_total_packetloss_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}",
     "legendFormat": "Control"
    }
   ]
  },
  {
   "title": "Bandwith last second",
   "type": "graph",
   "description": "Based on teamspeak_connection_bandwidth_received_last_second_total & teamspeak_connection_bandwidth_sent_last_second_total ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_second_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_second_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Bandwidth last minute",
   "type": "graph",
   "description": "Based on teamspeak_connection_bandwidth_received_last_minute_total &  teamspeak_connection_bandwidth_sent_last_minute_total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "teamspeak_connection_bandwidth_received_last_minute_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Incoming"
    },
    {
     "expr": "-teamspeak_connection_bandwidth_sent_last_minute_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} * 8",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Connection bytes",
   "type": "graph",
   "description": "Based on teamspeak_connection_bytes_received_total, teamspeak_connection_bytes_received_speech, teamspeak_connection_bytes_received_keepalive, teamspeak_connection_bytes_received_control, teamspeak_connection_bytes_sent_total, teamspeak_connection_bytes_sent_speech, teamspeak_connection_bytes_sent_keepalive, teamspeak_connection_bytes_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "irate(teamspeak_connection_bytes_received_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_bytes_received_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_bytes_sent_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "description": "Based on teamspeak_connection_packets_received_total, teamspeak_connection_packets_received_speech, teamspeak_connection_packets_received_keepalive, teamspeak_connection_packets_received_control, teamspeak_connection_packets_sent_total, teamspeak_connection_packets_sent_speech, teamspeak_connection_packets_sent_keepalive & teamspeak_connection_packets_sent_control",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(teamspeak_connection_packets_received_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming total"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming speech"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming keepalive"
    },
    {
     "expr": "irate(teamspeak_connection_packets_received_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Incoming control"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_total{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing total"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_speech{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing speech"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_keepalive{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing keepalive"
    },
    {
     "expr": "-irate(teamspeak_connection_packets_sent_control{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m]) * 8",
     "legendFormat": "Outgoing control"
    }
   ]
  },
  {
   "title": "Upload / Download",
   "type": "graph",
   "description": "Based on teamspeak_virtualserver_total_bytes_uploaded & teamspeak_virtualserver_total_bytes_downloaded",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(teamspeak_virtualserver_total_bytes_uploaded{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m])",
     "legendFormat": "Uploaded"
    },
    {
     "expr": "-irate(teamspeak_virtualserver_total_bytes_downloaded{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"}[5m])",
     "legendFormat": "Downloaded"
    }
   ]
  },
  {
   "title": "Average ping",
   "type": "graph",
   "description": "Based on teamspeak_virtualserver_total_ping",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "teamspeak_virtualserver_total_ping{instance=\"$instance\",job=\"$job\",virtualserver_name=\"$virtualserver\"} ",
     "legendFormat": "Ping"
    }
   ]
  }
 ]
}